In [4]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [6]:
x = np.linspace(-10, 10, 1000)
y = sigmoid(x)
print(x.min(), x.max())
print(y.min(), y.max())

-10.0 10.0
4.5397868702434395e-05 0.9999546021312976


In [7]:
x_new1 = [4, 5]
x_new2 = -2.5
y_pred1 = sigmoid(x_new1)
y_pred2 = sigmoid(x_new2)
plt.plot(x, y)
plt.scatter([x_new1], [y_pred1], c='g')
plt.scatter([x_new2], [y_pred2], c='r')
plt.axvline(x=0)
plt.show()

TypeError: bad operand type for unary -: 'list'

$$
Loss = -\frac{1}{N} \sum_{i=1}^N (y_i log(\hat{y_i}) + (1 - y_i) log(1 - \hat{y_i}))
$$

In [ ]:
x1      y_pred 0.99     y 1          e 0.01
x4      y_pred 0.6      y 1          e 0.51
x2      y_pred 0.1      y 0          e 0.1
x3      y_pred 0.95     y 0          e 2.9
x5      y_pred 0.12     y 1          e 2.12

In [ ]:
y_pred = 0.999
y = 0
-(y * np.log(y_pred) + (1 - y) * np.log(1 - y_pred))

np.float64(6.907755278982136)

$$
\hat{y} = \frac{1}{1 + e^{-(\hat{\beta}_0 + \hat{\beta}_1 x_1 + \hat{\beta}_2 x_2 + \dots + \hat{\beta}_k x_k)}}
$$

$$
\hat{y} = \frac{1}{1 + e^{-X\beta}}
$$

$$
\text{Loss}(\beta) = -\frac{1}{N} \sum_{i=1}^N (y_i log(\hat{y_i}) + (1 - y_i) log(1 - \hat{y_i}))
$$

$$
\frac{\partial \text{Loss}(\beta)}{\partial \beta} = -\frac{2}{N}X^T \varepsilon
$$

$$
-\frac{2}{N}X^T (y - \frac{1}{1 + e^{-X\beta}}) = 0
$$

In [ ]:
class LogisticRegression:
    def __init__(self, learning_rate, tol, max_iter):
        self.learning_rate = learning_rate
        ...

    def fit(self, X, y):

        return self
    
    def predict(self, X):
        pass

    def score(self, X, y):
        pass

In [ ]:
import pandas as pd

df = pd.read_csv('data/heart_diceases.csv')

X = df.drop(columns=['target']).values
y = df['target'].values

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

scl = StandardScaler()
X = scl.fit_transform(X)

log_reg = LogisticRegression()
log_reg.fit(X, y)

LogisticRegression()

In [ ]:
log_reg.coef_

array([[-0.07715302, -0.83306913,  0.86535401, -0.3125644 , -0.28394712,
        -0.03450706,  0.21491842,  0.53362203, -0.46532106, -0.66044518,
         0.32676576, -0.76541039, -0.54320814]])

In [ ]:
y_pred = log_reg.predict(X)

In [ ]:
y_pred[:20]

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1])

In [ ]:
y[:20]

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1])

In [ ]:
log_reg.score(X, y)

0.8585365853658536

Accuracy
Precision
Recall
f1_score
confusion matrix